version: '3.4'

services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10

  rr_db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_DATABASE: rr_govwifi
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10

  wifi_user_db:
    build: ./mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_DATABASE: wifi_user_govwifi
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      args:
        BUNDLE_INSTALL_FLAGS: "${BUNDLE_INSTALL_FLAGS:- --jobs 20 --retry 5}"
    links:
      - db
      - rr_db
      - wifi_user_db
    depends_on:
      db:
        condition: service_healthy
      rr_db:
        condition: service_healthy
      wifi_user_db:
        condition: service_healthy
    expose:
    - "3000"
