---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: "((readonly_private_ecr_repo_url))"
    tag: concourse-builder-latest

# https://github.com/concourse/builder-task#params
params:
  CONTEXT: src
  BUILD_ARG_BUNDLE_INSTALL_FLAGS: '--without test development'
  TAG:

inputs:
  - name: src

outputs:
  - name: image

caches:
  - path: cache

run:
  path: sh
  args:
    - '-exc'
    - |
      echo "$TAG" > image/tag
      build
