---
platform: linux

params:
  STAGE:
  AWS_ACCESS_KEY_ID:
  AWS_DEFAULT_REGION:
  AWS_SECRET_ACCESS_KEY:

  # These are set for deploy.sh and migrate.sh
  SERVICE_NAME: "admin"
  CLUSTER_NAME: "admin-cluster"
  TASK_NAME: "admin-task"
  CONTAINER_NAME: "admin"

inputs:
  - name: src
  - name: deploy-tools

run:
  path: bash
  args:
    - '-exc'
    - |
      src/tasks/scripts/migrate.sh
      src/tasks/scripts/deploy.sh
