---
platform: linux

inputs:
  - name: src
  - name: docker-cache/mysql-image
  - name: docker-cache/nginx-image
  - name: docker-cache/ruby-image
  - name: docker-cache/app-prebuilt

params:
  ON_CONCOURSE: true

run:
  path: src/ci/tasks/scripts/lint.sh
