---
platform: linux

inputs:
  - name: src
  - name: docker-cache/mysql-image
  - name: docker-cache/nginx-image
  - name: docker-cache/ruby-image

outputs:
  # aligns with PREBUILT_TAG
  - name: docker-cache/app-prebuilt

caches:
  - path: docker-cache/app-prebuilt-cached

params:
  # Expose that we're using Concourse
  ON_CONCOURSE: true
  # Set this to custom image names for preloading the app image. see `docker-compose.concourse.yml`
  PREBUILT_TAG: 'app-prebuilt'
  PREBUILT_CACHED_DIR: 'docker-cache/app-prebuilt-cached'
  DOCKER_HUB_USERNAME_ENV: '((docker_hub_username))'
  DOCKER_HUB_AUTHTOKEN_ENV: '((docker_hub_authtoken))'

run:
  path: docker-wrapper
  args: [src/ci/tasks/scripts/pre-build.sh]
