staging:
  support_email: 'govwifi-support@digital.cabinet-office.gov.uk'
  confirmation_email:
    template_id: '1af17502-9797-4e61-904e-999f6cf259a5'
  notify_support_of_new_user:
    template_id: '79af3335-ab32-4c4b-9075-b9d7138c7e61'

development:
  support_email: 'dev@localhost'
  confirmation_email:
    template_id: '1af17502-9797-4e61-904e-999f6cf259a5'
  notify_support_of_new_user:
    template_id: '79af3335-ab32-4c4b-9075-b9d7138c7e61'

test:
  support_email: 'test@localhost'
  confirmation_email:
    template_id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  notify_support_of_new_user:
    template_id: 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy'

production:
  support_email: 'govwifi-support@digital.cabinet-office.gov.uk'
  confirmation_email:
    template_id: '5f42e490-ce5e-44e7-9104-805136961116'
  notify_support_of_new_user:
    template_id: 'fd79c7b9-48d7-4086-b62a-0fc6f56daa4b'
